[[releasenotes-24]]
== What's New in OpenNMS Horizon 24

* Added support for browser notifications to notifd.
  The browser notification can be added to a notification path and desktop notifications will pop-up for currently logged in users if a notice is delivered.
* Added support for user defined links (UDLs) in the Enhanced Linkd topology.
  Users may now programitically (using the REST API) create "manual" links between node and have them appear in the topology UI.

=== System Requirements

* *Java 8 through 11*: OpenNMS Horizon 24 requires at least Java 8 as the runtime environment and now supports running on JDK 11 as well.
  To run Horizon 24, we recommend the most recent version of Oracle JDK 8 for your platform, or the latest OpenJDK 11.
* *PostgreSQL 9 or higher*: Horizon 24 requires Any supported version PostgreSQL 9 or higher.
  As of this writing, PostgreSQL 9.3 is the earliest version under active support, but OpenNMS is known to work with at least PostgreSQL 9.1 and up.

=== Breaking Changes

* Flows are grouped by conversations using applications instead of ports.
  This changes the way statistics about flows are presented and grouped.
  Therefore the elasticsearch storage has changed and old data must be converted to the new format.
  To adopt existing flows, the following command can be used (please be aware that this can take a long time and put your CPU and disk under high stress):
+
```
curl -v -X POST -H 'Content-Type: application/json' "http://${ES_HOST}:${ES_PORT}/netflow-*/_update_by_query?refresh=true" -d @- << EOF
{
  "script": {
    "lang": "painless",
    "source": "ctx._source['netflow.convo_key'] = '[\"' + ctx._source['location'] + '\",' + ctx._source['netflow.protocol'] + ',\"' + ((Objects.compare(ctx._source['netflow.src_addr'], ctx._source['netflow.src_addr'], String::compareTo) < 0) ? ctx._source['netflow.src_addr'] : ctx._source['netflow.dst_addr']) + '\",\"' + ((Objects.compare(ctx._source['netflow.src_addr'], ctx._source['netflow.src_addr'], String::compareTo) < 0) ? ctx._source['netflow.dst_addr'] : ctx._source['netflow.src_addr']) + '\",' + ((ctx._source['netflow.application'] != null) ? ('\"' + ctx._source['netflow.application'] + '\"') : 'null') + ']'"
  },
  "query": {
    "match_all": {}
  }
}
EOF
```
* *Dhcpd*: The *Dhcpd* plugin (and its configuration) was removed in favor of a Minion-capable implementation.
  The new *DhcpMonitor* options can be set in the `poller-configuration.xml` file.
* The default parser used for Syslog messages has been switched from the `CustomSyslogParser` to the `RadixTreeSyslogParser`.
* Session timeout is now disabled by default.
* With introducing support for more dynamic telemetryd configurations to support more complex listeners and adapters, the configuration format has changed and must be adopted to the new format by the user.
  The new configuration defines listeners containing parsers and queues containing adapters which are linked by the queues name.
+
As an example, the old configuration:
+
```
<telemetryd-config>
  <protocol name="Netflow-5" description="Listener for Netflow 5 UDP packets" enabled="false">
    <listener name="Netflow-5-UDP-8877" class-name="org.opennms.netmgt.telemetry.listeners.udp.UdpListener">
      <parameter key="port" value="8877"/>
    </listener>

    <adapter name="Netflow-5-Parser" class-name="org.opennms.netmgt.telemetry.adapters.netflow.v5.Netflow5Adapter">
    </adapter>
  </protocol>
</telemetryd-config>
```
+
versus the same configuration adopted to the new format:
+
```
<telemetryd-config>
  <listener name="Netflow-5-UDP-8877" class-name="org.opennms.netmgt.telemetry.listeners.UdpListener" enabled="false">
    <parameter key="port" value="8877"/>

    <parser name="Netflow-5-Parser" class-name="org.opennms.netmgt.telemetry.protocols.netflow.parser.Netflow5UdpParser" queue="Netflow-5" />
  </listener>

  <queue name="Netflow-5">
    <adapter name="Netflow-5-Adapter" class-name="org.opennms.netmgt.telemetry.protocols.netflow.adapter.netflow5.Netflow5Adapter" enabled="false">
    </adapter>
  </queue>
</telemetryd-config>
```
+
As you can see, the ``listener``s become independent elements which contain ``parser``s whereas the ``protocol``s are renamed to ``queue``s.
Each parser must reference a queue by name to define which adapters are used to pick up the parsed data.
+
In addition, the listener configuration for minions has changed, too.
The new minion configuration looks like the following and adapts the same set of structural changes:
+
```
admin@minion()> config:edit --alias Netflow-5-UDP-8877 --factory org.opennms.features.telemetry.listeners
admin@minion()> config:property-set name Netflow-5-UDP-8877
admin@minion()> config:property-set class-name org.opennms.netmgt.telemetry.listeners.UdpListener
admin@minion()> config:property-set parameters.port 8877
admin@minion()> config:property-set parser.0.name Netflow-5-Parser
admin@minion()> config:property-set parser.0.queue Netflow-5
admin@minion()> config:property-set parser.0.class-name org.opennms.netmgt.telemetry.protocols.netflow.parser.Netflow5UdpParser
```

=== New Features

=== Other Improvements

* list of notable issues not covered elsewhere
